name: Run fsi-sync on docker02

on:
  # Moved to AWS ECS Scheduled Task
  # schedule:
  #   - cron: '23 20 * * *' # 6AM AEDST

  # Enable manual trigger
  workflow_dispatch:  

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  CONTAINER_NAME: fsi-sync

jobs:
  run-fsi-sync:
    # specific self-hosted runner docker02
    runs-on: docker02

    steps:
    
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Run Docker container
        run: |
          docker run --rm -d --name ${{ env.CONTAINER_NAME }} \
            --env-file ${{ secrets.ENV_STAGING_FILE_PATH }} \
            --log-driver syslog --log-opt syslog-address=udp://syslog.kambala.nsw.edu.au:5141 \
            --log-opt tag=${{ env.CONTAINER_NAME }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C06P76V4X5F'
          # For posting a simple plain text message
          slack-message: "${{ github.workflow }} ${{ job.status }} - ${{ env.IMAGE_NAME }}\n"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}